int x = 6;
int y = 2;
println("Integer addition/subtraction:");
println("x = %d, y = %d.  x +  y => %d",  x, y, (x + y));
println("x = %d, y = %d.  x -  y => %d",  x, y, (x - y));
println("x = %d, y = %d. -x + -y => %d", x, y, (-x + -y));
println("Integer multiplication/division:");
println("x = %d, y = %d. x * y => %d",  x, y, (x * y));
println("x = %d, y = %d. x / y => %d",  x, y, (x / y));
println("Integer comparison:");
println("x = %d, y = %d. x == y => %d", x, y, (x == y));
println("x = %d, y = %d. x != y => %d", x, y, (x != y));
println("x = %d, y = %d. x >  y => %d",  x, y, (x > y));
println("x = %d, y = %d. x >= y => %d", x, y, (x >= y));
println("x = %d, y = %d. x <  y => %d",  x, y, (x < y));
println("x = %d, y = %d. x <= y => %d", x, y, (x <= y));
